name: Ubuntu

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: clean cache
      run: npm cache clean --force

    - name: install
      run: npm ci

    - name: npm install
      run: npm install

    - name: build
      env: GENERATE_SOURCEMAP: false
      run: npm run build

    - name: archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: develop_snapshot
        path: build
