name: Ubuntu

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: |
        nvm use
        yarn
    - name: build
      run: npm run build
    # - name: Archive artifacts
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: develop_snapshot
    #     path: /home/runner/work/snapweb/snapweb/public
