name: Ubuntu

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Print environment
      run: env

    - name: Get dependencies
      run: sudo apt-get update && sudo apt-get install -yq debhelper
      env:
        DEBIAN_FRONTEND: noninteractive

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Update npm
      run: npm install -g npm@latest

    - name: Clean npm cache
      run: npm cache clean --force

    - name: Install
      run: npm ci

    - name: Build
      env: 
        GENERATE_SOURCEMAP: "false"
      run: npm run build

    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: develop_snapshot
        path: build

    - name: Create changelog
      run: |
        $GITHUB_WORKSPACE/debian/changelog_md2deb.py $GITHUB_WORKSPACE/changelog.md > $GITHUB_WORKSPACE/debian/changelog
        cat $GITHUB_WORKSPACE/debian/changelog

    - name: Create deb package
      env:
        GENERATE_SOURCEMAP: "false"
      run: |
        fakeroot make -f debian/rules clean
        fakeroot make -f debian/rules binary

    - name: Archive deb artifacts
      uses: actions/upload-artifact@v4
      with:
        name: snapweb
        path: ${{env.PARENT_DIR}}/snapweb_*.deb
